### ISSUE TITLE
Kibana 5.6 failed to start

### ISSUE THREAD

**Issue by pprishchepa** [wodby/kibana#1] opened 2019-02-21 12:08 UTC
The issue caused by [--max-http-header-size=65536](https://github.com/elastic/kibana/blob/5.6/bin/kibana#L24) (related [PR](https://github.com/elastic/kibana/pull/27921/files)).

Error message:
```
kibana_1         | /usr/share/kibana/bin/../node/bin/node: bad option: --max-http-header-size=65536
```

**Comment by jeffnyman** [comment] 2019-03-02 11:24
Just ran into this myself and wanted to double check. What does this mean in terms of resolving it? I'm seeing the linked PR talks about Node 6.16.0. Node is well past that version even for LTS. And I bring that up only because I'm wondering what this means for us who have Node installed? For example, I'm getting this same error and it shows as:

    /Users/jeff/.nvm/versions/node/v10.13.0/bin/node: bad option: --max-http-header-size=65536

This happens when running `.bin/kibana` just to start it up. (I'm using version 6.6.1 of Kibana.) But note that's referencing my own Node installation, which is well beyond 6.x.x. I wasn't sure from Pavel's message if Kibana had to be running its own local version of Node or how the reference PR would even work in a situation like mine where Node is beyond 6.x.x but is still showing the problem.

**Comment by pprishchepa** [comment] 2019-03-04 05:06
This issue affects [Kibana v5.6](https://travis-ci.org/wodby/kibana/builds/495649437) only. Referenced PR is a commit where "bad option" `--max-http-header-size` option has been added. You may use the latest successfully built docker image `wodby/kibana:5.6-3.0.3` until this issue will be solved.

**Comment by jeffnyman** [comment] 2019-03-04 10:06
If this is only supposed to be for 5.6, then I can confirm it's happening on 6.6.1 as well, as I mentioned above with my Kibana version. I'm getting Kibana from https://www.elastic.co/downloads/kibana.

**Comment by pprishchepa** [comment] 2019-03-04 10:20
You should open an issue in Kibana project then. This project is about `wodby/kibana` docker image only.

**Comment by jeffnyman** [comment] 2019-03-04 12:04
Ach! Good point. My apologies. This was the first link that popped up when I looked for causes and effects and I should have been better about making sure this was the right place. Again, my apologies on that.

**Comment by pprishchepa** [comment] 2019-03-27 04:30
@csandanov it seems I've [found](https://github.com/elastic/kibana/pull/33827) the cause of the issue. We have to set up Node.js of a version specified in `.node-version` file in Kibana instead of setting up the latest one from the alpine packages.

**Comment by csandanov** [comment] 2019-03-27 06:15
5.6 has reached EOL https://www.elastic.co/support/eol, we will drop it.

**Comment by csandanov** [comment] 2019-03-27 06:18
Ok, although the 5.6 has reached EOL it is still maintained until 7.0 GA release. So, we should keep it as the last of 5.x branch for the time being and instead drop 5.3, 5.4

**Comment by csandanov** [comment] 2019-04-01 07:39
Fixed in 4.0.0

**Closed as completed by csandanov** 2019-04-01 07:39 UTC
Labels: bug

**Comment by avisual** [comment] 2019-05-08 21:39
seeing this in 7.0.1

**Comment by iukea1** [comment] 2019-06-09 16:19
> seeing this in 7.0.1

have you found a work arround? I am just now hitting this issue.

**Comment by avisual** [comment] 2019-06-09 17:34
Nope 

Regards

John Harrison

**Comment by askot** [comment] 2019-06-09 18:21
As a workaround you can remove '--max-http-header-size=65536' option from nodejs in bin/kibana. The error comes from new nodejs version not supporting this parameter.

**Comment by csandanov** [comment] 2019-06-10 04:44
It seems you guys have this error with Kibana that unrelated to this image. The issue was fixed in **this specific image** by using nodejs version specified by kibana. So I'm locking it now. If you still have a problem with this image please submit a new issue.
